"""Modified Users Table

Revision ID: 2a00fd6c3143
Revises: 2fa92b05616d
Create Date: 2022-12-08 13:25:16.552075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a00fd6c3143'
down_revision = '2fa92b05616d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_fname', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('user_lname', sa.String(length=30), nullable=False))
        batch_op.drop_index('user_name')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=32), nullable=False))
        batch_op.create_index('user_name', ['user_name'], unique=False)
        batch_op.drop_column('user_lname')
        batch_op.drop_column('user_fname')

    # ### end Alembic commands ###
