"""Created Users Table

Revision ID: 2fa92b05616d
Revises: 777f3ee623b2
Create Date: 2022-12-06 17:29:59.804253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa92b05616d'
down_revision = '777f3ee623b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=32), nullable=False),
    sa.Column('user_email', sa.String(length=64), nullable=False),
    sa.Column('user_pwd', sa.String(length=128), nullable=False),
    sa.Column('user_role', sa.String(length=12), nullable=False),
    sa.Column('user_budget', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_name')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['product_owner_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_owner_id')

    op.drop_table('users')
    # ### end Alembic commands ###
