"""First Migrate

Revision ID: 777f3ee623b2
Revises: 
Create Date: 2022-12-06 17:11:46.375840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777f3ee623b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=40), nullable=False),
    sa.Column('product_desc', sa.Text(), nullable=False),
    sa.Column('product_code', sa.String(length=12), nullable=False),
    sa.Column('product_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_code'),
    sa.UniqueConstraint('product_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
